In [1]:
import codecs
import pandas as pd
from datetime import datetime
from statsbombpy import sb

In [2]:
#Load in Statsbomb competition and match data
#This is a library for loading json files.
import json

#Load the competition file
competitions = pd.read_json(codecs.open('../Statsbomb/data/competitions.json','r','utf-8'))

In [3]:
competitions.head()

,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,9,27,Germany,1. Bundesliga,male,False,False,2015/2016,2023-08-17T23:51:11.837478,None,None,2023-08-17T23:51:11.837478
1,16,4,Europe,Champions League,male,False,False,2018/2019,2023-03-07T12:20:48.118250,2021-06-13T16:17:31.694,None,2023-03-07T12:20:48.118250
2,16,1,Europe,Champions League,male,False,False,2017/2018,2021-08-27T11:26:39.802832,2021-06-13T16:17:31.694,None,2021-01-23T21:55:30.425330
3,16,2,Europe,Champions League,male,False,False,2016/2017,2021-08-27T11:26:39.802832,2021-06-13T16:17:31.694,None,2020-07-29T05:00
4,16,27,Europe,Champions League,male,False,False,2015/2016,2021-08-27T11:26:39.802832,2021-06-13T16:17:31.694,None,2020-07-29T05:00

In [4]:
laLiga = competitions[competitions['competition_name']=='La Liga'].reset_index()

In [5]:
laLiga.head()

,index,competition_id,season_id,country_name,competition_name,competition_gender,competition_youth,competition_international,season_name,match_updated,match_updated_360,match_available_360,match_available
0,35,11,90,Spain,La Liga,male,False,False,2020/2021,2023-07-26T14:11:01.312143,2023-07-26T14:15:15.217027,2023-07-26T14:15:15.217027,2023-07-26T14:11:01.312143
1,36,11,42,Spain,La Liga,male,False,False,2019/2020,2023-07-25T00:16:32.999467,2021-06-13T16:17:31.694,None,2023-07-25T00:16:32.999467
2,37,11,4,Spain,La Liga,male,False,False,2018/2019,2023-08-03T02:24:43.761907,2021-07-09T14:53:22.103024,None,2023-08-03T02:24:43.761907
3,38,11,1,Spain,La Liga,male,False,False,2017/2018,2023-07-24T13:03:48.574627,2021-06-13T16:17:31.694,None,2023-07-24T13:03:48.574627
4,39,11,2,Spain,La Liga,male,False,False,2016/2017,2023-07-25T00:14:55.260536,2021-06-13T16:17:31.694,None,2023-07-25T00:14:55.260536

In [6]:
comp_id = laLiga['competition_id'][0]

In [7]:
messiYears = list(range(2004,2022))

In [8]:
messiLaLiga =[]
messiSeasons =[]
for y in messiYears:
    for index, row in laLiga.iterrows():
        if(str(y) in row['season_name']):
            if(row['season_id'] in messiLaLiga):
                pass
            else:
                messiLaLiga.append(row['season_id'])
                messiSeasons.append(y)

In [9]:
messiLaLiga

[37, 38, 39, 40, 41, 21, 22, 23, 24, 25, 26, 27, 2, 1, 4, 42, 90]

In [10]:
messiSeasons[0]

2004

In [11]:
temp = pd.read_json(codecs.open('../Statsbomb/data/matches/11/1.json',"r","utf-8"))

In [12]:
#Load the list of matches for this competition
col = temp.columns.tolist()
matches = pd.DataFrame(columns=col)
count = 0
for i in messiLaLiga:
    match = pd.read_json(codecs.open('../Statsbomb/data/matches/'+str(comp_id)+"/"+str(i)+".json","r","utf-8"))
    match['season'] = messiSeasons[count]
    count = count+1
    matches = pd.concat([matches, match])

FileNotFoundError: [Errno 2] No such file or directory: '../Statsbomb/data/matches/11/4.json'

In [ ]:
matches.head(1)

,match_id,match_date,kick_off,competition,season,home_team,away_team,home_score,away_score,match_status,match_status_360,last_updated,last_updated_360,metadata,match_week,competition_stage,stadium,referee
0,68314,2004-12-04,20:00:00.000,"{'competition_id': 11, 'country_name': 'Spain'...",2004,"{'home_team_id': 217, 'home_team_name': 'Barce...","{'away_team_id': 223, 'away_team_name': 'Málag...",4,0,available,scheduled,2020-07-29T05:00,2021-06-13T16:17:31.694,"{'data_version': '1.1.0', 'shot_fidelity_versi...",14,"{'id': 1, 'name': 'Regular Season'}","{'id': 342, 'name': 'Spotify Camp Nou', 'count...","{'id': 993, 'name': 'José Omar Losantos', 'cou..."

In [ ]:
matches = matches.drop(['kick_off','competition','match_status','match_status_360','last_updated','last_updated_360','metadata','competition_stage'],axis=1)

In [ ]:
matches['match_date'] = pd.to_datetime(matches['match_date'],format="%Y-%m-%d")

In [ ]:
matches['home_team'].iloc[0]

{'home_team_id': 217,
 'home_team_name': 'Barcelona',
 'home_team_gender': 'male',
 'home_team_group': None,
 'country': {'id': 214, 'name': 'Spain'},
 'managers': [{'id': 4953,
   'name': 'Frank Rijkaard',
   'nickname': None,
   'dob': '1962-09-30',
   'country': {'id': 160, 'name': 'Netherlands'}}]}

In [ ]:
manager=[]
oppManager=[]
homeTeam = []
awayTeam = []
stadium =[]
referee=[]
for index,row in matches.iterrows():
    try:
        if(row['home_team']['home_team_id']==217):
            manager.append(row['home_team']['managers'][0]['name'])
        else:
            manager.append(row['away_team']['managers'][0]['name'])
    except:
        manager.append('NA')
    try:
        if(row['home_team']['home_team_id']==217):
            oppManager.append(row['away_team']['managers'][0]['name'])
        else:
            oppManager.append(row['home_team']['managers'][0]['name'])            
    except:
        oppManager.append('NA')
    
    homeTeam.append(row['home_team']['home_team_name'])
    awayTeam.append(row['away_team']['away_team_name'])
    stadium.append(row['stadium']['name'])
    try:
        referee.append(row['referee']['name'])
    except:
        referee.append('NA')
    
matches['home_team_name'] = homeTeam
matches['away_team_name'] = awayTeam
matches['manager'] = manager
matches['opp_manager'] = oppManager
matches['stadium'] = stadium
matches['referee'] = referee

In [ ]:
matches[matches['manager']=='NA'].head()

,match_id,match_date,season,home_team,away_team,home_score,away_score,match_week,stadium,referee,home_team_name,away_team_name,manager,opp_manager
1,68324,2006-01-22,2005,"{'home_team_id': 217, 'home_team_name': 'Barce...","{'away_team_id': 206, 'away_team_name': 'Depor...",2,0,20,Spotify Camp Nou,Turienzo,Barcelona,Deportivo Alavés,NA,NA
4,69172,2006-02-18,2005,"{'home_team_id': 217, 'home_team_name': 'Barce...","{'away_team_id': 218, 'away_team_name': 'Real ...",5,1,24,Spotify Camp Nou,Eduardo Iturralde Gonzalez,Barcelona,Real Betis,NA,NA
10,68350,2006-02-05,2005,"{'home_team_id': 217, 'home_team_name': 'Barce...","{'away_team_id': 212, 'away_team_name': 'Atlét...",1,3,22,Spotify Camp Nou,Vicente José Lizondo Cortés,Barcelona,Atlético Madrid,NA,NA
3,68333,2007-02-25,2006,"{'home_team_id': 217, 'home_team_name': 'Barce...","{'away_team_id': 215, 'away_team_name': 'Athle...",3,0,24,Spotify Camp Nou,Vicente José Lizondo Cortés,Barcelona,Athletic Club,NA,NA
6,69162,2007-05-13,2006,"{'home_team_id': 217, 'home_team_name': 'Barce...","{'away_team_id': 218, 'away_team_name': 'Real ...",1,1,34,Spotify Camp Nou,Eduardo Iturralde Gonzalez,Barcelona,Real Betis,NA,NA

In [ ]:
count=0
for index,row in matches.iterrows():
    if(row['home_team_name']=='Barcelona'):
        if(row['manager']=='NA'):
            if(manager[count-1] != 'NA' and manager[count+1]!='NA' and manager[count-1]==manager[count+1]):
                manager[count] = manager[count-1]
    else:
        if(row['manager']=='NA'):
            if(manager[count-1] != 'NA' and manager[count+1]!='NA' and manager[count-1]==manager[count+1]):
                manager[count] = manager[count-1]
        
    count=count+1

In [ ]:
matches['manager'] = manager

In [ ]:
matches[matches['manager']=='NA']

,match_id,match_date,season,home_team,away_team,home_score,away_score,match_week,stadium,referee,home_team_name,away_team_name,manager,opp_manager
0,266015,2012-12-22,2012,"{'home_team_id': 901, 'home_team_name': 'Real ...","{'away_team_id': 217, 'away_team_name': 'Barce...",1,3,17,Estadio Municipal José Zorrilla,Carlos Clos Gómez,Real Valladolid,Barcelona,NA,NA
1,70270,2012-09-22,2012,"{'home_team_id': 217, 'home_team_name': 'Barce...","{'away_team_id': 1049, 'away_team_name': 'Gran...",2,0,5,Spotify Camp Nou,NA,Barcelona,Granada,NA,NA
2,70281,2013-05-05,2012,"{'home_team_id': 217, 'home_team_name': 'Barce...","{'away_team_id': 218, 'away_team_name': 'Real ...",4,2,34,Spotify Camp Nou,Carlos Clos Gómez,Barcelona,Real Betis,NA,NA
3,70308,2012-11-03,2012,"{'home_team_id': 217, 'home_team_name': 'Barce...","{'away_team_id': 209, 'away_team_name': 'Celta...",3,1,10,Spotify Camp Nou,David Fernández Borbalan,Barcelona,Celta Vigo,NA,NA
4,70282,2013-02-03,2012,"{'home_team_id': 207, 'home_team_name': 'Valen...","{'away_team_id': 217, 'away_team_name': 'Barce...",1,1,22,Estadio de Mestalla,José Luis González González,Valencia,Barcelona,NA,NA
5,266724,2012-11-11,2012,"{'home_team_id': 1043, 'home_team_name': 'Mall...","{'away_team_id': 217, 'away_team_name': 'Barce...",2,4,11,Estadi Mallorca Son Moix,Ignacio Iglesias Villanueva,Mallorca,Barcelona,NA,NA
6,70272,2013-03-02,2012,"{'home_team_id': 220, 'home_team_name': 'Real ...","{'away_team_id': 217, 'away_team_name': 'Barce...",2,1,26,Estadio Santiago Bernabéu,Miguel Pérez,Real Madrid,Barcelona,NA,NA
7,70304,2012-10-20,2012,"{'home_team_id': 219, 'home_team_name': 'RC De...","{'away_team_id': 217, 'away_team_name': 'Barce...",4,5,8,Estadio Abanca-Riazor,José Paradas,RC Deportivo La Coruña,Barcelona,NA,NA
8,70280,2012-11-25,2012,"{'home_team_id': 221, 'home_team_name': 'Levan...","{'away_team_id': 217, 'away_team_name': 'Barce...",0,4,13,Estadio Ciudad de Valencia,Pedro Jesús Pérez Montero,Levante UD,Barcelona,NA,NA
9,70296,2012-12-16,2012,"{'home_team_id': 217, 'home_team_name': 'Barce...","{'away_team_id': 212, 'away_team_name': 'Atlét...",4,1,16,Spotify Camp Nou,Miguel Pérez,Barcelona,Atlético Madrid,NA,NA
10,70297,2013-02-10,2012,"{'home_team_id': 217, 'home_team_name': 'Barce...","{'away_team_id': 216, 'away_team_name': 'Getaf...",6,1,23,Spotify Camp Nou,Ignacio Iglesias Villanueva,Barcelona,Getafe,NA,NA
11,266433,2013-01-06,2012,"{'home_team_id': 217, 'home_team_name': 'Barce...","{'away_team_id': 214, 'away_team_name': 'Espan...",4,0,18,Spotify Camp Nou,Jesús Gil Manzano,Barcelona,Espanyol,NA,NA
12,70256,2013-03-30,2012,"{'home_team_id': 209, 'home_team_name': 'Celta...","{'away_team_id': 217, 'away_team_name': 'Barce...",2,2,29,Abanca-Balaídos,Antonio Miguel Mateu Lahoz,Celta Vigo,Barcelona,NA,NA
13,70259,2012-08-19,2012,"{'home_team_id': 217, 'home_team_name': 'Barce...","{'away_team_id': 210, 'away_team_name': 'Real ...",5,1,1,Spotify Camp Nou,José Luis González González,Barcelona,Real Sociedad,NA,NA
14,70260,2013-01-27,2012,"{'home_team_id': 217, 'home_team_name': 'Barce...","{'away_team_id': 422, 'away_team_name': 'Osasu...",5,1,21,Spotify Camp Nou,Fernando Teixeira,Barcelona,Osasuna,NA,NA
15,70263,2012-12-01,2012,"{'home_team_id': 217, 'home_team_name': 'Barce...","{'away_team_id': 215, 'away_team_name': 'Athle...",5,1,14,Spotify Camp Nou,Antonio Miguel Mateu Lahoz,Barcelona,Athletic Club,NA,NA
17,70287,2013-01-19,2012,"{'home_team_id': 210, 'home_team_name': 'Real ...","{'away_team_id': 217, 'away_team_name': 'Barce...",3,2,20,Reale Arena,Alberto Undiano Mallenco,Real Sociedad,Barcelona,NA,NA
18,70284,2013-05-12,2012,"{'home_team_id': 212, 'home_team_name': 'Atlét...","{'away_team_id': 217, 'away_team_name': 'Barce...",1,2,35,Estadio Vicente Calderón,Pedro Jesús Pérez Montero,Atlético Madrid,Barcelona,NA,NA
19,70275,2012-09-29,2012,"{'home_team_id': 213, 'home_team_name': 'Sevil...","{'away_team_id': 217, 'away_team_name': 'Barce...",2,3,6,Estadio Ramón Sánchez Pizjuán,Antonio Miguel Mateu Lahoz,Sevilla,Barcelona,NA,NA
20,70286,2012-09-02,2012,"{'home_team_id': 217, 'home_team_name': 'Barce...","{'away_team_id': 207, 'away_team_name': 'Valen...",1,0,3,Spotify Camp Nou,Miguel Pérez,Barcelona,Valencia,NA,NA
21,70309,2012-11-17,2012,"{'home_team_id': 217, 'home_team_name': 'Barce...","{'away_team_id': 395, 'away_team_name': 'Real ...",3,1,12,Spotify Camp Nou,Miguel Ayza,Barcelona,Real Zaragoza,NA,NA
22,70300,2012-10-07,2012,"{'home_team_id': 217, 'home_team_name': 'Barce...","{'away_team_id': 220, 'away_team_name': 'Real ...",2,2,7,Spotify Camp Nou,Carlos Delgado,Barcelona,Real Madrid,NA,NA
23,70295,2012-12-09,2012,"{'home_team_id': 218, 'home_team_name': 'Real ...","{'away_team_id': 217, 'away_team_name': 'Barce...",1,2,15,Estadio Benito Villamarín,Carlos Velasco Carballo,Real Betis,Barcelona,NA,NA
24,70307,2013-03-17,2012,"{'home_team_id': 217, 'home_team_name': 'Barce...","{'away_team_id': 360, 'away_team_name': 'Rayo ...",3,1,28,Spotify Camp Nou,José Luis González González,Barcelona,Rayo Vallecano,NA,NA
25,70305,2013-03-09,2012,"{'home_team_id': 217, 'home_team_name': 'Barce...","{'away_team_id': 219, 'away_team_name': 'RC De...",2,0,27,Spotify Camp Nou,Pedro Jesús Pérez Montero,Barcelona,RC Deportivo La Coruña,NA,NA
26,266827,2013-01-13,2012,"{'home_team_id': 223, 'home_team_name': 'Málag...","{'away_team_id': 217, 'away_team_name': 'Barce...",1,3,19,Estadio La Rosaleda,Carlos Delgado,Málaga,Barcelona,NA,NA
28,70271,2013-02-23,2012,"{'home_team_id': 217, 'home_team_name': 'Barce...","{'away_team_id': 213, 'away_team_name': 'Sevil...",2,1,25,Spotify Camp Nou,Carlos Velasco Carballo,Barcelona,Sevilla,NA,NA
29,70294,2013-02-16,2012,"{'home_team_id': 1049, 'home_team_name': 'Gran...","{'away_team_id': 217, 'away_team_name': 'Barce...",1,2,24,Estadio Nuevo Los Cármenes,NA,Granada,Barcelona,NA,NA
30,70262,2012-08-26,2012,"{'home_team_id': 422, 'home_team_name': 'Osasu...","{'away_team_id': 217, 'away_team_name': 'Barce...",1,2,2,Estadio El Sadar,César Muñiz,Osasuna,Barcelona,NA,NA
31,70292,2012-09-15,2012,"{'home_team_id': 216, 'home_team_name': 'Getaf...","{'away_team_id': 217, 'away_team_name': 'Barce...",1,4,4,Coliseum Alfonso Pérez,Fernando Teixeira,Getafe,Barcelona,NA,NA
0,267368,2014-04-05,2013,"{'home_team_id': 217, 'home_team_name': 'Barce...","{'away_team_id': 218, 'away_team_name': 'Real ...",3,1,32,Spotify Camp Nou,Eduardo Prieto Iglesias,Barcelona,Real Betis,NA,NA

In [ ]:
i=0
for man in manager:
    if(man=='NA'):
        if(matches.iloc[i]['season']==2012):
            manager[i] = 'Tito Vilanova'
        elif(matches.iloc[i]['season']==2013):
            manager[i] = 'Gerardo Daniel Martino'            
    i=i+1

In [ ]:
matches['manager'] = manager

In [ ]:
matches[matches['manager']=='NA']

Empty DataFrame
Columns: [match_id, match_date, season, home_team, away_team, home_score, away_score, match_week, stadium, referee, home_team_name, away_team_name, manager, opp_manager]
Index: []

In [ ]:
matches.head(1)

,match_id,match_date,season,home_team,away_team,home_score,away_score,match_week,stadium,referee,home_team_name,away_team_name,manager,opp_manager
0,68314,2004-12-04,2004,"{'home_team_id': 217, 'home_team_name': 'Barce...","{'away_team_id': 223, 'away_team_name': 'Málag...",4,0,14,Spotify Camp Nou,José Omar Losantos,Barcelona,Málaga,Frank Rijkaard,Gregorio Manzano Ballesteros

In [ ]:
matches = matches.drop(['home_team','away_team'],axis=1)

In [ ]:
matches.head(1)

,match_id,match_date,season,home_score,away_score,match_week,stadium,referee,home_team_name,away_team_name,manager,opp_manager
0,68314,2004-12-04,2004,4,0,14,Spotify Camp Nou,José Omar Losantos,Barcelona,Málaga,Frank Rijkaard,Gregorio Manzano Ballesteros

In [ ]:
matches=matches[['match_id','match_date','match_week','season','home_team_name','away_team_name','home_score','away_score','manager','opp_manager','stadium','referee']]

In [ ]:
barca = matches[(matches['home_team_name']=='Barcelona') | (matches['away_team_name'] == 'Barcelona')]

In [ ]:
match_id = barca['match_id']

In [ ]:
temp = pd.read_json(codecs.open('../Statsbomb/data/lineups/266142.json',"r","utf-8"))

In [ ]:
temp.head()

   team_id  team_name                                             lineup
0      213    Sevilla  [{'player_id': 3497, 'player_name': 'Vicente I...
1      217  Barcelona  [{'player_id': 3958, 'player_name': 'Pedro Eli...

In [ ]:
temp = pd.DataFrame(temp[temp['team_id']==217]['lineup'])

In [ ]:
col = temp.columns.tolist()
lineups = pd.DataFrame(columns=col)
for i in match_id:
    lu = pd.read_json(codecs.open('../Statsbomb/data/lineups/'+str(i)+".json","r","utf-8"))
    try:
        lineup=pd.DataFrame(lu[lu['team_id']==217]['lineup'][0])
    except:
        lineup=pd.DataFrame(lu[lu['team_id']==217]['lineup'][1])        
    lineup['match_id'] = i
    lineups = pd.concat([lineups, lineup])

In [ ]:
upid = lineups['player_id'].unique()

In [ ]:
upid

array([  5216.,   5503.,   5558.,   6913.,  17797.,  19298.,  19757.,
        20125.,  20131.,  20176.,  25854.,  25863.,  25873.,  25879.,
        25878.,   4325.,   6730.,  25896.,  26409.,   8193.,  15743.,
        19296.,  25910.,  25949.,  40827.,  25925.,  11270.,  15071.,
        15774.,  25962.,   3087.,   4913.,   5987.,  15516.,  20177.,
        25919., 147331.,  26005.,  26506.,  26507.,  12772.,   4324.,
         5203.,  18882.,  20169.,   5213.,   6758.,   5248.,   3958.,
        26638.,   3672.,   5208.,  18608.,  26613.,  26624.,   6357.,
         7068.,   4891.,   5506.,  12737.,  22102.,   6724.,   6593.,
         6890.,   6692.,  47490.,   3385.,   3478.,   6658.,  26776.,
         6560.,   6379.,   3726.,   5211.,  27053.,   4320.,  25831.,
         4691.,   5246.,   5470.,   6998.,  10609.,  20055.,   3508.,
         6616.,  27318.,   6332.,  11302.,   6834.,  21229.,  19392.,
         6400.,  11094.,   3362.,   5492.,   6402.,   6609.,   6849.,
         8652.,  10802.,  27251.,  13599.,  22235.,  30476.,  24194.,
        13108.,   3501.,   5477.,   5542.,   6374.,   6196.,   6810.,
        13597.,  17804.,   6826.,   8206.,   3109.,  11392.,  41407.,
        22197.,   6585.,  37237.,   8668.,   5674.,  24841.,  24976.,
        25006.,  11532.,  35404.,   4447.,   5487.,   6590.,   8118.,
        17304.,  20734.,  30756.,  24949.,  32480.,  41122.,  41543.,
        41641.,  39159.,  41408.,  23987.,   6947.,  21881.,  22390.,
        30486.,  39469.,  29256.,  39073.,  43728.,  49301.])

In [ ]:
player_name = pd.DataFrame(columns=['player_id','player_name'])
for pid in upid:
    player_name.loc[len(player_name)] = [pid, lineups[lineups['player_id']==pid]['player_nickname'].iloc[0]]

In [ ]:
messiLU = lineups[lineups['player_nickname']=='Lionel Messi']

In [ ]:
messiLU

,lineup,player_id,player_name,player_nickname,jersey_number,country,cards,positions,match_id
1,NaN,5503.0,Lionel Andrés Messi Cuccittini,Lionel Messi,30.0,"{'id': 11, 'name': 'Argentina'}",[],"[{'position_id': 3, 'position': 'Right Center ...",68314.0
1,NaN,5503.0,Lionel Andrés Messi Cuccittini,Lionel Messi,30.0,"{'id': 11, 'name': 'Argentina'}",[],"[{'position_id': 21, 'position': 'Left Wing', ...",68313.0
2,NaN,5503.0,Lionel Andrés Messi Cuccittini,Lionel Messi,30.0,"{'id': 11, 'name': 'Argentina'}",[],"[{'position_id': 23, 'position': 'Center Forwa...",68316.0
1,NaN,5503.0,Lionel Andrés Messi Cuccittini,Lionel Messi,19.0,"{'id': 11, 'name': 'Argentina'}",[],"[{'position_id': 2, 'position': 'Right Back', ...",68315.0
1,NaN,5503.0,Lionel Andrés Messi Cuccittini,Lionel Messi,19.0,"{'id': 11, 'name': 'Argentina'}",[],"[{'position_id': 2, 'position': 'Right Back', ...",69153.0
...,...,...,...,...,...,...,...,...,...
6,NaN,5503.0,Lionel Andrés Messi Cuccittini,Lionel Messi,10.0,"{'id': 11, 'name': 'Argentina'}","[{'time': '73:16', 'card_type': 'Yellow Card',...","[{'position_id': 17, 'position': 'Right Wing',...",3773547.0
7,NaN,5503.0,Lionel Andrés Messi Cuccittini,Lionel Messi,10.0,"{'id': 11, 'name': 'Argentina'}",[],"[{'position_id': 23, 'position': 'Center Forwa...",3773415.0
7,NaN,5503.0,Lionel Andrés Messi Cuccittini,Lionel Messi,10.0,"{'id': 11, 'name': 'Argentina'}",[],"[{'position_id': 23, 'position': 'Center Forwa...",3764440.0
6,NaN,5503.0,Lionel Andrés Messi Cuccittini,Lionel Messi,10.0,"{'id': 11, 'name': 'Argentina'}",[],"[{'position_id': 22, 'position': 'Right Center...",3773689.0
6,NaN,5503.0,Lionel Andrés Messi Cuccittini,Lionel Messi,10.0,"{'id': 11, 'name': 'Argentina'}",[],"[{'position_id': 22, 'position': 'Right Center...",3773477.0

In [ ]:
messiMatchID = messiLU['match_id']

In [ ]:
messiMatches = barca[barca['match_id'].isin(messiMatchID)]

In [ ]:
messiMatches

,match_id,match_date,match_week,season,home_team_name,away_team_name,home_score,away_score,manager,opp_manager,stadium,referee
0,68314,2004-12-04,14,2004,Barcelona,Málaga,4,0,Frank Rijkaard,Gregorio Manzano Ballesteros,Spotify Camp Nou,José Omar Losantos
1,68313,2004-10-24,8,2004,Barcelona,Osasuna,3,0,Frank Rijkaard,Javier Aguirre Onaindía,Spotify Camp Nou,Vicente José Lizondo Cortés
2,68316,2005-05-01,34,2004,Barcelona,Albacete,2,0,Frank Rijkaard,Martín Monteagudo Monteagudo,Spotify Camp Nou,Carlos Velasco Carballo
3,68315,2004-12-21,17,2004,Barcelona,Levante UD,2,1,Frank Rijkaard,Bernd Schuster,Spotify Camp Nou,David Fernández Borbalan
4,69153,2004-12-11,15,2004,Albacete,Barcelona,1,2,Frank Rijkaard,José Manuel González López,Estadio Carlos Belmonte,Alfonso Perez Burrull
...,...,...,...,...,...,...,...,...,...,...,...,...
30,3773547,2020-11-29,11,2020,Barcelona,Osasuna,4,0,Ronald Koeman,Jagoba Arrasate Elustondo,Spotify Camp Nou,Antonio Miguel Mateu Lahoz
31,3773415,2021-02-21,24,2020,Barcelona,Cádiz,1,1,Ronald Koeman,Álvaro Cervera Díaz,Spotify Camp Nou,Juan Martínez Munuera
32,3764440,2021-02-24,1,2020,Barcelona,Elche,3,0,Ronald Koeman,Francisco Escriba Segura,Spotify Camp Nou,Isidro Díaz de Mera Escuderos
33,3773689,2021-04-25,32,2020,Villarreal,Barcelona,1,2,Ronald Koeman,Unai Emery Etxegoien,Estadio de la Cerámica,Carlos del Cerro Grande
34,3773477,2020-11-07,9,2020,Barcelona,Real Betis,5,2,Ronald Koeman,Manuel Luis Pellegrini Ripamonti,Spotify Camp Nou,NA

In [ ]:
messiMatchesG = messiMatches.groupby('season').agg(lambda x: list(x)).reset_index()

In [ ]:
messiMatchesG

,season,match_id,match_date,match_week,home_team_name,away_team_name,home_score,away_score,manager,opp_manager,stadium,referee
0,2004,"[68314, 68313, 68316, 68315, 69153, 68352, 68353]","[2004-12-04 00:00:00, 2004-10-24 00:00:00, 200...","[14, 8, 34, 17, 15, 32, 7]","[Barcelona, Barcelona, Barcelona, Barcelona, A...","[Málaga, Osasuna, Albacete, Levante UD, Barcel...","[4, 3, 2, 2, 1, 2, 0]","[0, 0, 0, 1, 2, 0, 1]","[Frank Rijkaard, Frank Rijkaard, Frank Rijkaar...","[Gregorio Manzano Ballesteros, Javier Aguirre ...","[Spotify Camp Nou, Spotify Camp Nou, Spotify C...","[José Omar Losantos, Vicente José Lizondo Cort..."
1,2005,"[69164, 68324, 68320, 68323, 69172, 68339, 683...","[2005-10-26 00:00:00, 2006-01-22 00:00:00, 200...","[11, 20, 14, 17, 24, 10, 18, 13, 25, 6, 22, 21...","[Barcelona, Barcelona, Villarreal, Barcelona, ...","[Málaga, Deportivo Alavés, Barcelona, Celta Vi...","[2, 2, 0, 2, 5, 1, 1, 4, 0, 2, 1, 0, 2, 0, 2, ...","[0, 0, 2, 0, 1, 3, 2, 1, 2, 2, 3, 3, 1, 3, 1, ...","[Frank Rijkaard, Frank Rijkaard, Frank Rijkaar...","[Antonio Tapia Flores, NA, Manuel Luis Pellegr...","[Spotify Camp Nou, Spotify Camp Nou, Estadio d...","[Puentes Leira, Turienzo, César Muñiz, Miguel ..."
2,2006,"[69176, 69179, 68334, 68333, 68336, 68326, 691...","[2007-05-20 00:00:00, 2007-04-07 00:00:00, 200...","[35, 29, 25, 24, 38, 1, 34, 26, 23, 7, 6, 27, ...","[Atlético Madrid, Real Zaragoza, Sevilla, Barc...","[Barcelona, Barcelona, Barcelona, Athletic Clu...","[0, 1, 2, 3, 1, 2, 1, 3, 2, 2, 3, 0, 2, 2, 2, ...","[6, 0, 1, 0, 5, 3, 1, 3, 1, 0, 1, 4, 2, 0, 0, ...","[Frank Rijkaard, Frank Rijkaard, Frank Rijkaar...","[Javier Aguirre Onaindía, Victor Fernández Bra...","[Estadio Vicente Calderón, Estadio de la Romar...","[César Muñiz, Luis Medina Cantalejo, Bernardin..."
3,2007,"[69151, 69144, 69169, 68360, 69186, 69180, 691...","[2007-09-29 00:00:00, 2007-10-07 00:00:00, 200...","[6, 7, 2, 25, 38, 1, 5, 21, 26, 12, 8, 15, 33,...","[Levante UD, Barcelona, Barcelona, Barcelona, ...","[Barcelona, Atlético Madrid, Athletic Club, Le...","[1, 3, 3, 5, 3, 0, 4, 1, 4, 2, 3, 2, 0, 1, 2, ...","[4, 0, 1, 1, 5, 0, 1, 1, 2, 0, 1, 1, 0, 1, 0, ...","[Frank Rijkaard, Frank Rijkaard, Frank Rijkaar...","[Abel Resino Gómez, Javier Aguirre Onaindía, J...","[Estadio Ciudad de Valencia, Spotify Camp Nou,...","[Carlos Clos Gómez, Eduardo Iturralde Gonzalez..."
4,2008,"[69225, 69212, 69235, 69232, 69216, 69209, 692...","[2008-12-13 00:00:00, 2008-10-04 00:00:00, 200...","[15, 6, 9, 8, 26, 21, 22, 35, 29, 30, 31, 23, ...","[Barcelona, Barcelona, Málaga, Barcelona, Barc...","[Real Madrid, Atlético Madrid, Barcelona, Alme...","[2, 6, 1, 5, 2, 1, 3, 3, 0, 2, 0, 2, 2, 4, 6, ...","[0, 1, 4, 0, 0, 2, 1, 3, 1, 0, 1, 2, 2, 3, 0, ...","[Josep Guardiola i Sala, Josep Guardiola i Sal...","[Juan de la Cruz Ramos Cano, Javier Aguirre On...","[Spotify Camp Nou, Spotify Camp Nou, Estadio L...","[Luis Medina Cantalejo, Eduardo Iturralde Gonz..."
5,2009,"[69243, 69241, 69239, 69257, 69253, 69244, 692...","[2010-01-16 00:00:00, 2010-05-04 00:00:00, 201...","[18, 36, 37, 28, 8, 35, 9, 2, 17, 13, 10, 38, ...","[Barcelona, Barcelona, Sevilla, Barcelona, Bar...","[Sevilla, Tenerife, Barcelona, Osasuna, Real Z...","[4, 4, 2, 2, 6, 1, 1, 0, 0, 1, 4, 4, 1, 0, 0, ...","[0, 1, 3, 0, 1, 4, 1, 2, 5, 3, 2, 0, 0, 1, 2, ...","[Josep Guardiola i Sala, Josep Guardiola i Sal...","[Manuel Enrique Jiménez Jiménez, José Luis Olt...","[Spotify Camp Nou, Spotify Camp Nou, Estadio R...","[Carlos Delgado, Carlos Delgado, Alberto Undia..."
6,2010,"[69276, 69304, 69307, 69271, 69305, 69278, 692...","[2011-02-05 00:00:00, 2011-04-02 00:00:00, 201...","[22, 30, 14, 33, 31, 19, 16, 20, 10, 29, 32, 2...","[Barcelona, Villarreal, Osasuna, Barcelona, Ba...","[Atlético Madrid, Barcelona, Barcelona, Osasun...","[3, 0, 0, 2, 3, 4, 1, 3, 1, 2, 1, 0, 0, 2, 1, ...","[0, 1, 3, 0, 1, 1, 5, 0, 3, 1, 1, 2, 3, 1, 2, ...","[Josep Guardiola i Sala, Josep Guardiola i Sal...","[Enrique Sánchez Flores, Juan Carlos Garrido F...","[Spotify Camp Nou, Estadio de la Cerámica, Est...","[Turienzo, Rafael Ramírez Domínguez, Fernando ..."
7,2011,"[69328, 69329, 70219, 69331, 69337, 69322, 693...","[2012-02-19 00:00:00, 2011-10-22 00:00:00, 201...","[24, 9, 32, 13, 25, 27, 22, 17, 1, 12, 6, 30, ...","[Barcelona, Barcelona, Real Zaragoza, Barcelon...","[Valencia, Sevilla, Barcelona, Real Zaragoza, ...","[5, 0, 1, 4, 1, 0, 2, 4, 1, 2, 5, 0, 1, 5, 3, ...","[1, 0, 4, 0, 2, 2, 1, 0, 4, 2, 0, 2, 2, 3, 0, ...","[Josep Guardiola i Sala, Josep Guardiola i Sal...","[Unai Emery Etxegoien, Marcelino García Toral,...","[Spotify Camp Nou, Spotify Camp Nou, Estadio d...","[Turienzo, Eduardo Iturralde Gonzalez, Turienz..."
8,2012,"[266015, 70270, 70281, 70308, 70282, 266724, 7...","[2012-12-22 00:00:00, 2012-09-22 00:00:00, 201...","[17, 5, 34, 10, 22, 11, 26, 8, 13, 16, 23, 18,...","[Real Valladolid, Barcelona, Barcelona, Barcel...","[Barcelona, Granada, Real Betis, Celta Vigo, B...","[1, 2, 4, 3, 1, 2, 2, 4, 0, 4, 6, 4, 2, 5, 5, ...","[3, 0, 2, 1, 1, 4, 1, 5, 4, 1, 1, 0, 2, 1, 1, ...","[Tito Vilanova, Tito Vilanova, Tito Vilanova, ...","[NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N...","[Estadio Municipal José Zorrilla, Spotify Camp...","[Carlos Clos Gómez, NA, Carlos Clos Gómez, Dav..."
9,2013,"[267368, 70301, 70298, 70302, 70291, 267138, 2...","[2014-04-05 00:00:00, 2013-09-14 00:00:00, 201...","[32, 4, 3, 5, 21, 33, 6, 35, 26, 23, 20, 28, 3...","[Barcelona, Barcelona, Valencia, Rayo Vallecan...","[Real Betis, Sevilla, Barcelona, Barcelona, Má...","[3, 3, 2, 0, 3, 1, 4, 2, 4, 1, 1, 7, 2, 0, 3, ...","[1, 2, 3, 4, 0, 0, 1, 3, 1, 4, 1, 0, 1, 0, 0, ...","[Gerardo Daniel Martino, Gerardo Daniel Martin...","[NA, Unai Emery Etxegoien, Miroslav Đukić, Fra...","[Spotify Camp Nou, Spotify Camp Nou, Estadio d...","[Eduardo Prieto Iglesias, César Muñiz, José Te..."
10,2014,"[267183, 265835, 266838, 265963, 266117, 26691...","[2015-03-22 00:00:00, 2014-11-22 00:00:00, 201...","[28, 12, 5, 34, 6, 26, 38, 15, 3, 10, 8, 35, 3...","[Barcelona, Barcelona, Málaga, Barcelona, Barc...","[Real Madrid, Sevilla, Barcelona, Getafe, Gran...","[2, 5, 0, 6, 6, 6, 2, 0, 2, 0, 3, 0, 4, 0, 3, ...","[1, 1, 0, 0, 0, 1, 2, 0, 0, 1, 0, 8, 0, 1, 1, ...","[Luis Enrique Martínez García, Luis Enrique Ma...","[Carlo Ancelotti, Unai Emery Etxegoien, Javier...","[Spotify Camp Nou, Spotify Camp Nou, Estadio L...","[Antonio Miguel Mateu Lahoz, NA, NA, David Fer..."
11,2015,"[266498, 266986, 267533, 266310, 267576, 26665...","[2016-03-12 00:00:00, 2016-04-30 00:00:00, 201...","[29, 36, 31, 34, 22, 27, 35, 21, 37, 6, 2, 1, ...","[Barcelona, Real Betis, Barcelona, RC Deportiv...","[Getafe, Barcelona, Real Madrid, Barcelona, At...","[6, 0, 1, 0, 2, 1, 6, 1, 5, 2, 1, 0, 1, 2, 4, ...","[0, 2, 2, 8, 1, 5, 0, 2, 0, 1, 0, 1, 1, 2, 0, ...","[Luis Enrique Martínez García, Luis Enrique Ma...","[Francisco Escriba Segura, Juan Merino Ruíz, Z...","[Spotify Camp Nou, Estadio Benito Villamarín, ...","[Pedro Jesús Pérez Montero, Antonio Miguel Mat..."
12,2016,"[266989, 266357, 267569, 267212, 266669, 26689...","[2016-11-06 00:00:00, 2016-12-10 00:00:00, 201...","[11, 15, 33, 4, 3, 2, 5, 1, 20, 37, 17, 34, 28...","[Sevilla, Osasuna, Real Madrid, Leganés, Barce...","[Barcelona, Barcelona, Barcelona, Barcelona, D...","[1, 0, 2, 1, 1, 0, 1, 6, 1, 1, 1, 7, 4, 2, 2, ...","[2, 3, 3, 5, 2, 1, 1, 2, 1, 4, 1, 1, 2, 3, 1, ...","[Luis Enrique Martínez García, Luis Enrique Ma...","[Jorge Luis Sampaoli Moya, Joaquín de Jesús Ca...","[Estadio Ramón Sánchez Pizjuán, Estadio El Sad...","[NA, NA, NA, NA, NA, Antonio Miguel Mateu Laho..."
13,2017,"[9880, 9912, 9924, 9855, 9827, 9799, 9636, 960...","[2018-04-14 00:00:00, 2018-04-29 00:00:00, 201...","[32, 35, 36, 29, 26, 24, 7, 5, 1, 34, 17, 18, ...","[Barcelona, RC Deportivo La Coruña, Barcelona,...","[Valencia, Barcelona, Real Madrid, Athletic Cl...","[2, 2, 2, 2, 1, 0, 3, 6, 2, 5, 0, 3, 0, 0, 5, ...","[1, 4, 2, 0, 1, 2, 0, 1, 0, 1, 3, 0, 5, 2, 0, ...","[Ernesto Valverde Tejedor, Ernesto Valverde Te...","[Marcelino García Toral, Clarence Seedorf, Zin...","[Spotify Camp Nou, Estadio Abanca-Riazor, Spot...","[Carlos del Cerro Grande, Ricardo De Burgos Be..."
14,2018,"[15978, 15998, 16029, 16073, 16086, 16190, 161...","[2018-09-15 00:00:00, 2018-09-26 00:00:00, 201...","[4, 6, 9, 13, 15, 25, 17, 18, 24, 28, 23, 33, ...","[Real Sociedad, Leganés, Barcelona, Atlético M...","[Barcelona, Barcelona, Sevilla, Barcelona, Bar...","[1, 2, 4, 1, 0, 2, 2, 1, 1, 1, 0, 2, 3, 2, 3, ...","[2, 1, 2, 1, 4, 4, 0, 2, 0, 4, 0, 1, 0, 2, 1, ...","[Ernesto Valverde Tejedor, Ernesto Valverde Te...","[Asier Garitano Aguirrezábal, Mauricio Pellegr...","[Reale Arena, Estadio Municipal de Butarque, S...","[Carlos del Cerro Grande, Alberto Undiano Mall..."
15,2019,"[303731, 303532, 303516, 303596, 303430, 30372...","[2020-02-22 00:00:00, 2020-06-16 00:00:00, 202...","[25, 29, 32, 10, 6, 34, 12, 16, 17, 22, 21, 37...","[Barcelona, Barcelona, Celta Vigo, Barcelona, ...","[Eibar, Leganés, Barcelona, Real Madrid, Villa...","[5, 2, 2, 0, 2, 1, 3, 5, 2, 2, 2, 1, 0, 1, 0, ...","[0, 0, 2, 0, 1, 4, 1, 2, 2, 1, 0, 2, 5, 0, 1, ...","[Enrique Setién Solar, Enrique Setién Solar, E...","[José Luis Mendilibar Etxebarria, Javier Aguir...","[Spotify Camp Nou, Spotify Camp Nou, Abanca-Ba...","[NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, Jesús..."
16,2020,"[3773386, 3773565, 3773457, 3773631, 3773665, ...","[2020-10-31 00:00:00, 2021-01-09 00:00:00, 202...","[8, 18, 37, 22, 26, 30, 13, 3, 4, 7, 17, 5, 6,...","[Deportivo Alavés, Granada, Barcelona, Real Be...","[Barcelona, Barcelona, Celta Vigo, Barcelona, ...","[1, 0, 1, 2, 0, 2, 1, 4, 0, 1, 0, 1, 1, 1, 2, ...","[1, 4, 2, 3, 2, 1, 0, 0, 3, 3, 1, 1, 0, 0, 2, ...","[Ronald Koeman, Ronald Koeman, Ronald Koeman, ...","[Pablo Javier Machín Díez, Diego Martínez Pena...","[Estadio de Mendizorroza, Estadio Nuevo Los Cá...","[NA, Ricardo De Burgos Bengoetxea, NA, NA, Gui..."

In [ ]:
messiID = lineups[lineups['player_nickname']=='Lionel Messi']['player_id'][0]

In [ ]:
tempE = sb.competition_events(
            country="Spain",
            division= "La Liga",
            season="1973/1974"
        )

C:\Users\yashaswi\AppData\Roaming\Python\Python311\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

In [ ]:
col = tempE.columns.tolist()
eventsMessi = pd.DataFrame(columns=col)
seasons = messiMatchesG['season']
seasons.tolist().sort()
i=0
for season in laLiga['season_name']:
    if(season!='1973/1974'):
        event = sb.competition_events(
            country="Spain",
            division= "La Liga",
            season=season
        )
        event['season'] = season
        eventsMessi = pd.concat([eventsMessi, event[event['player_id']==messiID]])
    i=i+1

C:\Users\yashaswi\AppData\Roaming\Python\Python311\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\yashaswi\AppData\Local\Temp\ipykernel_30532\1249780555.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  event['season'] = season
C:\Users\yashaswi\AppData\Local\Temp\ipykernel_30532\1249780555.py:14: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  eventsMessi = pd.concat([eventsMessi, event[event['player_id']==messiID]])
C:\Users\yashaswi\AppData\Roaming\Python\Python311\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\yashaswi\AppData\Local\Temp\ipykernel_30532\1249780555.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  event['season'] = season
C:\Users\yashaswi\AppData\Roaming\Python\Python311\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\yashaswi\AppData\Local\Temp\ipykernel_30532\1249780555.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  event['season'] = season
C:\Users\yashaswi\AppData\Roaming\Python\Python311\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\yashaswi\AppData\Local\Temp\ipykernel_30532\1249780555.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  event['season'] = season
C:\Users\yashaswi\AppData\Roaming\Python\Python311\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\yashaswi\AppData\Local\Temp\ipykernel_30532\1249780555.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  event['season'] = season
C:\Users\yashaswi\AppData\Roaming\Python\Python311\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\yashaswi\AppData\Local\Temp\ipykernel_30532\1249780555.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  event['season'] = season
C:\Users\yashaswi\AppData\Roaming\Python\Python311\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\yashaswi\AppData\Local\Temp\ipykernel_30532\1249780555.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  event['season'] = season
C:\Users\yashaswi\AppData\Roaming\Python\Python311\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\yashaswi\AppData\Local\Temp\ipykernel_30532\1249780555.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  event['season'] = season
C:\Users\yashaswi\AppData\Roaming\Python\Python311\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\yashaswi\AppData\Local\Temp\ipykernel_30532\1249780555.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  event['season'] = season
C:\Users\yashaswi\AppData\Roaming\Python\Python311\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\yashaswi\AppData\Local\Temp\ipykernel_30532\1249780555.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  event['season'] = season
C:\Users\yashaswi\AppData\Roaming\Python\Python311\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\yashaswi\AppData\Local\Temp\ipykernel_30532\1249780555.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  event['season'] = season
C:\Users\yashaswi\AppData\Roaming\Python\Python311\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\yashaswi\AppData\Local\Temp\ipykernel_30532\1249780555.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  event['season'] = season
C:\Users\yashaswi\AppData\Roaming\Python\Python311\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\yashaswi\AppData\Local\Temp\ipykernel_30532\1249780555.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  event['season'] = season
C:\Users\yashaswi\AppData\Roaming\Python\Python311\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\yashaswi\AppData\Local\Temp\ipykernel_30532\1249780555.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  event['season'] = season
C:\Users\yashaswi\AppData\Roaming\Python\Python311\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\yashaswi\AppData\Local\Temp\ipykernel_30532\1249780555.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  event['season'] = season
C:\Users\yashaswi\AppData\Roaming\Python\Python311\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
C:\Users\yashaswi\AppData\Local\Temp\ipykernel_30532\1249780555.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  event['season'] = season
C:\Users\yashaswi\AppData\Roaming\Python\Python311\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

In [ ]:
eventsMessi.head()

,ball_receipt_outcome,ball_recovery_offensive,ball_recovery_recovery_failure,carry_end_location,clearance_aerial_won,clearance_body_part,clearance_head,clearance_left_foot,clearance_right_foot,counterpress,...,shot_saved_to_post,season,goalkeeper_lost_in_play,goalkeeper_success_in_play,half_start_late_video_start,goalkeeper_lost_out,player_off_permanent,goalkeeper_success_out,half_end_early_video_end,goalkeeper_saved_to_post
222,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2020/2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
224,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2020/2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
241,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2020/2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
269,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2020/2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
307,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2020/2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
eventsMessi['location']

222      [49.1, 56.9]
224      [61.9, 34.5]
241      [79.7, 59.7]
269      [77.7, 58.1]
307      [92.0, 49.6]
             ...
21609    [97.9, 63.3]
21713    [31.7, 15.0]
21719    [86.8, 19.6]
21852    [81.8, 22.2]
21926    [28.4, 24.5]
Name: location, Length: 115201, dtype: object

In [ ]:
eventsMessi[eventsMessi['shot_outcome']=='Goal']

,ball_receipt_outcome,ball_recovery_offensive,ball_recovery_recovery_failure,carry_end_location,clearance_aerial_won,clearance_body_part,clearance_head,clearance_left_foot,clearance_right_foot,counterpress,...,shot_saved_to_post,season,goalkeeper_lost_in_play,goalkeeper_success_in_play,half_start_late_video_start,goalkeeper_lost_out,player_off_permanent,goalkeeper_success_out,half_end_early_video_end,goalkeeper_saved_to_post
136435,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2020/2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
136437,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2020/2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
136455,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2020/2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
136485,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2020/2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
136575,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2020/2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49668,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2005/2006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49764,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2005/2006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49766,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2005/2006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49835,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2005/2006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20302,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2004/2005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
d =eventsMessi[eventsMessi['type']=='Shot']

In [ ]:
d['shot_outcome'].unique()

array(['Blocked', 'Saved', 'Off T', 'Goal', 'Wayward', 'Post',
       'Saved to Post', 'Saved Off Target'], dtype=object)

In [ ]:
d

,ball_receipt_outcome,ball_recovery_offensive,ball_recovery_recovery_failure,carry_end_location,clearance_aerial_won,clearance_body_part,clearance_head,clearance_left_foot,clearance_right_foot,counterpress,...,shot_saved_to_post,season,goalkeeper_lost_in_play,goalkeeper_success_in_play,half_start_late_video_start,goalkeeper_lost_out,player_off_permanent,goalkeeper_success_out,half_end_early_video_end,goalkeeper_saved_to_post
136401,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2020/2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
136404,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2020/2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
136406,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2020/2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
136407,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2020/2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
136408,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2020/2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20249,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2004/2005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20267,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2004/2005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20302,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2004/2005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20320,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2004/2005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20323,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2004/2005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN